version: '2.2'

services:

  mongo:
    image: mongo:3.6.22
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
      - mongo-config:/data/configdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "crawler"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u crawler -p secret --authenticationDatabase admin --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"



  keycloak:
    image: jboss/keycloak:12.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/data/realm-export.json
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=postgres
      - JDBC_PARAMS=useSSL=false
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
      - ldap-host
    healthcheck:
      test: "curl -f http://keycloak:8080/auth || exit 1"
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - ./keycloak/:/opt/jboss/keycloak/data

  ldap-host:
    image: osixia/openldap:1.4.0
    container_name: ldap-host
    environment:
      - LDAP_ORGANISATION="OBSS Incrawler"
      - LDAP_DOMAIN=obss.com
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
    ports:
      - "389:389"
    volumes:
      - ./ldap/:/container/service/slapd/assets/config/bootstrap/ldif/custom/

  phpldapadmin-service:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin-service
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - "6443:443"
    depends_on:
      - ldap-host

volumes:
  mongodata:
  mongo-config:

